#debug: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/bh_margin_token?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/bh_margin_token?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://192.168.2.101/bh_margin_token?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
 #资源映射路径为/**，也可以使用/image/**，使用url访问的请求路径
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/static/
      suffix: .html
  resources:
    static-locations: classpath:/static/,classpath:/META-INF/resources/,file:D:\\dyonga\\java_codes\\margin_token
   ##配置hibernate 
  jpa:
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect         
    generate-ddl: true
    show-sql: true
    hbm2ddl: 
       auto: update
    entitymanager:
       packagesToScan: com.bhyh.model 
   
    
  jackson:
    default-property-inclusion: non-null
   #配置servlet  
  servlet:
    multipart:
      enabled: true
      # 文件上传大小控制
      max-file-size: 20MB
      max-request-size: 20MB
 ## Mybatis 配置
#mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  #mapper-locations: classpath:com/bhyh/dao/**/*Mapper.xml
  #type-aliases-package: com.bhyh.model      
  #configuration:
   # map-underscore-to-camel-case: true
server:  port: 8099
  #ip: 183.250.155.231
  ip: 192.168.1.89
video:
  video_type: mp4,m3u8,ts,avi,mkv,flv,wmv,mov,rmvb     
  #1024*1024*15  (15M)
  video_size: 15728640
img_res_summary:
  file2check: D:/dyonga/bh/JAVA/img_res_summary/file2check.txt  